name: Boss
version: 1.0.0
main: com.nate.boss.Boss
author: items
description: A plugin for managing bosses
api-version: 1.17
commands:
  boss:
    description: Boss main plugin command
    usage: /boss
  boss spawn:
    description: Spawns a boss
    permission: 
    usage: /boss spawn
